### ISSUE TITLE
[WeSplit]

### ISSUE THREAD

**Issue by visvamba** [alemohamad/100-Days-of-SwiftUI#1]
In the "Number of People" picker, after using it once, on subsequent taps, the picker is greyed out and disabled.

**Comment by alemohamad** [comment]
Do you have a solution for this? I can't find something right now. Please let me know. 😉

**Comment by visvamba** [comment]
I think it is an issue with the simulator. [From stackoverflow](https://stackoverflow.com/questions/60029218/why-picker-in-swiftui-works-just-one-time/60030004#60030004)

**Comment by alemohamad** [comment]
Oh, yeah, that's something that happens in the simulator more than once with SwiftUI. I'm making apps right now with SwiftUI to test the framework out (until this moment it's truly amazing) but it's still buggy for complex implementations. Thanks for pointing this out.
